name: 'Tests & Formatting'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  checks:
    runs-on: ubuntu-22.04

    steps:

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install --yes libjpeg-dev webp libpng-dev libavif-dev libheif-dev libopenjpip7 libvips-tools build-essential

      - name: Install ImageMagick 7 from source
        run: |
          sudo apt-get update
          sudo apt-get install --yes build-essential pkg-config libjpeg-dev libpng-dev libtiff-dev libwebp-dev libheif-dev libavif-dev libopenjp2-7-dev
          wget https://imagemagick.org/archive/ImageMagick.tar.gz
          tar xvzf ImageMagick.tar.gz
          cd ImageMagick-7*
          ./configure
          make
          sudo make install
          sudo ldconfig /usr/local/lib
          magick --version

      - name: Checkout repo
        uses: actions/checkout@v4

      # Version taken from .ruby-version file.
      # Also runs bundle install.
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - run: bundle exec rake test

      - run: bundle exec rubocop
